default:
  artifacts:
    paths:
      - public

lint:
  image: node:alpine
  cache:
    paths:
      - node_modules
  script:
    - npm install stylelint stylelint-config-standard -g --no-audit
    - stylelint style.css
  after_script:
    - mkdir public
    - mv *.* public

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  script:
    - apk add brotli
    - brotli public/*
  only:
    - master
