image: node:alpine

cache:
  paths:
    - node_modules

lint:
  script:
    - npm install csslint htmlhint -g --no-audit
    - csslint style.css
    - htmlhint index.html

pages:
  stage: deploy
  script:
    - mkdir public
    - mv *.* public
  artifacts:
    paths:
      - public
  only:
    - master
