default:
  artifacts:
    paths:
      - public

lint:
  image: node:alpine
  cache:
    paths:
      - .npm/
  script:
    - npm install --no-audit --cache .npm --prefer-offline
    - npx eslint
    - npx prettier --check .
  after_script:
    - mkdir public
    - mv *.* public

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  script:
    - apk add brotli
    - brotli public/*
  only:
    - master
