default:
  artifacts:
    paths:
      - public

lint:
  image: node:alpine
  cache:
    paths:
      - node_modules
  script:
    - npm install csslint htmlhint -g --no-audit
    - csslint style.css
    - htmlhint index.html
  after_script:
    - mkdir public
    - mv *.* public

pages:
  stage: deploy
  image: alpine
  script:
    - apk add brotli
    - cd public
    - brotli *
  only:
    - master
