default:
  artifacts:
    paths:
      - public

lint:
  image: node:alpine
  cache:
    paths:
      - node_modules
  before_script:
    - npm install csslint htmlhint -g --no-audit
  script:
    - csslint style.css
    - htmlhint index.html
  after_script:
    - mkdir public
    - mv *.* public

pages:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine
  before_script:
    - apk add brotli
  script:
    - brotli public/*
  only:
    - master
