language: python
cache: apt
addons:
  apt:
    packages: language-pack-en-base
python: 3.6
before_install: pip install --upgrade pip wheel
install: pip install 'Nikola[extras]'
script:
  - nikola bootswatch_theme -n readable -s readable
  - nikola build
notifications:
  email:
    on_success: change
    on_failure: always
